### ISSUE TITLE
Correct action pattern to use bindActionCreator

### ISSUE THREAD

**Issue by KamranAsif** [angular-redux/ng-redux#139]
I'm trying to use redux + angular in my application. I have my action defined as a service to get dependency injected services that I rely on for async requests.

In my view, I have to do store.dispatch(actionService.action()). I'd much prefer to use bindActionCreator to be able to call actionService.action().

My problem is that my actions are defined on their class, so the only thing I can do is:
```
let actions = bindActionCreator({
  foo1: actionService.foo, 
  foo2: actionService.foo2, .
  ..
});
```

Is there a better pattern to do this in angularjs?

**Comment by johanzhou8** [comment]
Did you try to put your action creators object in the `connect` function? The `connect` function will wrap the action creators for you so that you can directly call the action.
```
//in the controller
let actions = {
  foo1: actionService.foo, 
  foo2: actionService.foo2,
};
const unsubscribe = $ngRedux.connect(this.mapStateToThis, actions)(this);

//in the template
//controller as ctrl
<button ng-click='ctrl.foo1()'>Foo1</button>
```
Following links might be helpful:
[The example code](https://github.com/angular-redux/ng-redux/blob/master/examples/async/containers/app.js#L14) and [Redux: Using mapDispatchToProps() Shorthand Notation](https://egghead.io/lessons/javascript-redux-using-mapdispatchtoprops-shorthand-notation)
