### ISSUE TITLE
 ngRedux.connect mapStateToTarget  is a direct reference to the state object by consequence is really easy to mutate

### ISSUE THREAD

**Issue by parga** [angular-redux/ng-redux#81]
The use case is this: 

Inside my class I defined my `mapStateTarget` callback as:
`onUpdate (state) {
        return {
            model: state.model
        };
    }`

On the other side I have an input that needs to modify an attribute of the model (this model can have some data already), so the obvious html would be.

`<input type="text" ng-change="$ctrl.actionX($ctrl.model.name)" ng-model="$ctrl.model.name" />`

at this point everything looks great but...

`mapStateToTarget` callback is returning a direct reference from to `state.model` so any change on the input is **mutating** the state directly (this because ng-model has double binding implicit) before the action being triggered .  

I tried different ways to bind the value to the input without breaking the immutability (no success). angular does not expose any other way to handle changes on inputs[text]

One possible solution can be that mapStateTarget should receive a clone of the state.

any thoughts on this ?

**Comment by dmackerman** [comment]
We ran into this also. The workaround we came up with was something like this:

```js
class PhotoActionsComponent {
    constructor($ngRedux, $scope) {
        this.$ngRedux = $ngRedux;
        let unsubscribe = $ngRedux.connect(state => this.onUpdate(state))(this);
        $scope.$on('$destroy', unsubscribe);
    }

    // our photo actions only care about the photo that matches the id.
    onUpdate(state) {
        let photo = state.photos.filter(photo => photo.id == this.photoId)[0];
        return {
            photo: Object.assign({}, photo)
        };
    }
}
```

This way `this.photo` is bound to to a new Object, and updated each time the store is updated. This gets around the `ng-model` issues you were speaking of, because by default it does appear that `ng-model` mutates the current value, whereas I *thought* that it used `assign` under the hood to get around this. Hope this helps.

**Comment by parga** [comment]
and what about `ng-redux` doing something like this on the internals

```javascript
let _model = Object.assign({}, state.create.model);
Object.setPrototypeOf(_model,  Object.getPrototypeOf(state.create.model));
```

**Comment by davidtran** [comment]
+1 I am getting this issue too. The state is mutated by Angular object.

**Comment by yadue** [comment]
Any update for this?

**Comment by yadielar** [comment]
Actually, it's a shallow copy of the state object. So you should only encounter this problem if you're selecting a state slice with deeply nested objects.

See @e-schultz answer for details: [here](https://github.com/angular-redux/ng-redux/issues/33#issuecomment-152596696).

Also have in mind that if you provide your own connector function to `$ngRedux.connect` (instead of the usual `this`), you must do the object copying yourself, as show in the async example:

```js
constructor($ngRedux, $scope, AsyncActions) {
    const unsubscribe = $ngRedux.connect(this.mapStateToThis, AsyncActions)((selectedState, actions) => {
      this.componentWillReceiveStateAndActions(selectedState, actions);
      Object.assign(this, selectedState, actions); // Makes a copy of the selected state
    });
}
```

Perhaps all this could be mentioned in the docs under [connect](https://github.com/angular-redux/ng-redux#connectmapstatetotarget-mapdispatchtotargettarget)?

**Comment by deini** [comment]
As @yadielar mentioned it's a shallow copy, so its actually working as expected.

**Comment by rajatvijay** [comment]
Got the point that it is a shallow copy, not a direct reference.

But what if my state is a nested object, then ng-model can mutate it.

What could be a solution here? Something like this
 
`
maptStateToThis() {
    item: angular.copy(state.item)
}
`

where item has the following strcuture in the state: 
`
item: { data: {name: "stuff", price: 250}, timestamp: 21345676543 }
`

**This way we can avoid the mutation**

**Comment by AntJanus** [comment]
@rajatvijay angular.copy is the way to go. You can also use other methods to map/filter/reduce whatever data you're looking at in order to get a copy of only the stuff you need (like you did with `angular.copy(state.item)`. 

You don't have to make a copy if the data is read-only.

**Comment by AntJanus** [comment]
Since it is working as expected and on par with `react-redux`'s implementation, I'm going to close this one out.

**Comment by deini** [comment]
Another strategy is to use `ng-model-options` and use a getter/setter and call actions on the setter.
