### ISSUE TITLE
Use ng-redux with ES5 (at least without import), demo plunkr

### ISSUE THREAD

**Issue by maxime1992** [angular-redux/ng-redux#90]
Hi,

I tried to make a simple example on plunkr :
[https://plnkr.co/edit/OD15ZtcXQyD3jDTHtRn9?p=preview](https://plnkr.co/edit/OD15ZtcXQyD3jDTHtRn9?p=preview)

It's not working.

Here's the code in case the plunkr is updated : 

**counter.action.js**
```javascript
let INCREMENT = 'INCREMENT'
let DECREMENT = 'DECREMENT'

function increment() {
  return {
    type: INCREMENT
  }
}

function decrement() {
  return {
    type: INCREMENT
  }
}
```

**counter.reducer.js**
```javascript
function counter(state = 1, action) {
  switch (action.type) {
    case INCREMENT:
      return state++
      
    case DECREMENT:
      return state--
  
    default:
      return state
  }
}
```

**script.js**
```javascript
// Code goes here

let app = angular.module('app', ['ngRedux'])

app.config(($ngReduxProvider) => {
  // why is that not working ?
  // let reducer = Redux.combineReducers({counter: counter})
  
  // as previous line is saying that :
  // Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.
  // do not pass the reducer ...
  // $ngReduxProvider.createStoreWith(reducer)
  
  // and it seems to be working when created with createStoreWith
  $ngReduxProvider.createStoreWith({counter: counter})
});

app.controller('reduxTestCtrl', function($scope, $ngRedux) {
    let self = this;
    
    // state is ok :
    // Object {counter: 1}
    console.log($ngRedux.getState())
    
    $ngRedux.subscribe(() => {
      // not even called ?
      let state = $ngRedux.getState();
      console.log('$scope')
      console.log($scope)
    })
    
    let unsubscribe = $ngRedux.connect(self.mapStateToThis, {increment, decrement})(self)
    
    self.mapStateToThis = function(state) {
      // not even called ?
      console.log('state')
      console.log(state)
      
      return {
        value: state.counter
      }
    }
    
    // what if I want to increment the counter as soon as the controller is created ?
    // this.counter.increment()
})
```

Could you help me figure out why it's not working and answer the questions in **script.js** ?

Thanks a lot !

**Comment by wbuchwalter** [comment]
Hey,

You'll find a corrected plunkr [here](https://plnkr.co/edit/rRQx3yKjcqaZ62tdcHvd?p=preview).

**counter.reducer.js**
```js
switch (action.type) {
    case INCREMENT:
         return state++
}
```
`state++` means you return the state and **then** increment, so you are never modifying the state.
Instead, you need to do `return ++state`, same thing for `case DECREMENT`.

**script.js**
```javascript
  // why is that not working ?
  let reducer = Redux.combineReducers({counter: counter})
```

This was a bug in the latest beta version of `ng-redux`, it is fixed now. Don't know how fast GitHub CDN cache is refreshed though, so in my plunker I just copy/pasted the content of `ng-redux` in a new file.
 
 ```js   
    $ngRedux.subscribe(() => {
      // not even called ?
      let state = $ngRedux.getState();
      console.log('$scope')
      console.log($scope)
    })
```
It is being called correctly whenever an action is dispatched. 

```js    
 let unsubscribe = $ngRedux.connect(self.mapStateToThis, {increment, decrement})(self)
    
    self.mapStateToThis = function(state) {
      // not even called ?
      return {
        value: state.counter
      }
    }
```
`mapStateToThis` is not being called because you define it after using it. JS's hoisting won't  save you in this case because your doing `self.mapStateToThis` and not referencing the function directly.
You just need to define the function before `connect`

```js
    // what if I want to increment the counter as soon as the controller is created ?
    // this.counter.increment()
```
`connect` will bind the action you specified (`increment` and `decrement`) to the target (`self` in your case).
So just do `self.increment()`.
Note: `$ngRedux` will go through `mapStateToThis` once as soon as it is connected so your component is correctly initialized. So if you wanted to call `increment` just to initialize the component, you don't need to do that.

**Comment by maxime1992** [comment]
@wbuchwalter thank you so much ! Really helpful.

Cheers !
