### ISSUE TITLE
Injectable store enhancers

### ISSUE THREAD

**Issue by iamFIREcracker** [angular-redux/ng-redux#98]
Where do you stand on changing `ngReduxProvider.$get()` implementation to support store enhancers being specified as strings (ie. injectable services, a la middlewares)?  If interested I could submit a PR.

**Comment by wbuchwalter** [comment]
I don't see any problem with that off the top of my head.
So I would say PR welcome :)

**Comment by iamFIREcracker** [comment]
And PR it is: https://github.com/angular-redux/ng-redux/pull/99 ;-)

**Comment by wbuchwalter** [comment]
Sorry for the delay, busy times on my side.
Since I have no time at all to test the changes, I have released this under `3.4.0-beta1`.
Please try that for some times, and if everything works fine let me know and I will release properly.
Keep in mind that this release also includes #89 .
Thank you.

P.S: I'm looking for collaborators for this repos, since I have a hard time supporting it alone now. If you are interested ping me on twitter or at wbuchwalter at gmail.
